[tool.black]
line-length = 95
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
include_trailing_comma = true
line_length = 100
multi_line_output = 3
skip_glob = ["**/migrations/*","**/grpc/*"]
use_parentheses = true

